# Generated by Django 5.2.10 on 2026-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('scenario_used', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scores', models.JSONField(default=dict)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
    ]
