# Generated by Django 5.2.10 on 2026-01-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='overall_score',
            field=models.FloatField(default=0.0),
        ),
    ]
